import os
import base64
import tempfile
import re
from flask import Flask, request, jsonify, render_template
from flask_cors import CORS
from rembg import remove, new_session
import vtracer

# ==========================================
# 1 CPU CORE OPTIMIZATION
# ==========================================
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"

app = Flask(__name__)
CORS(app)

# Initialize the AI session once in memory
print("Loading AI Background Removal Model...")
session = new_session("u2net")

@app.route('/')
def index():
    # Serves the V4 Frontend UI
    return render_template('index.html')

@app.route('/api/process-image', methods=['POST'])
def process_image():
    if 'file' not in request.files:
        return jsonify({'detail': 'No file part'}), 400
        
    file = request.files['file']
    
    if file.filename == '' or not file.filename.lower().endswith('.png'):
        return jsonify({'detail': 'Only .png files are supported'}), 400

    temp_png_path = None
    temp_svg_path = None

    try:
        input_bytes = file.read()
        print(f"[AI Engine V4] Processing: {file.filename}")

        # 1. PERFECT CUT: Alpha Matting enabled
        bg_removed_data = remove(
            input_bytes,
            session=session,
            alpha_matting=True,
            alpha_matting_foreground_threshold=240,
            alpha_matting_background_threshold=10,
            alpha_matting_erode_size=5
        )

        # 2. CREATE TEMPORARY FILES
        with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as temp_png:
            temp_png.write(bg_removed_data)
            temp_png_path = temp_png.name

        temp_svg_path = temp_png_path + ".svg"

        # 3. CLEAN SVG VECTORIZATION (The Classic, Perfected Method)
        print("[AI Engine V4] Tracing vectors...")
        vtracer.convert_image_to_svg_py(
            temp_png_path,
            temp_svg_path,
            colormode='color',
            hierarchical='stacked',
            mode='spline',
            filter_speckle=10,     
            color_precision=8,     
            layer_difference=16,
            corner_threshold=60,
            length_threshold=4.0,
            max_iterations=10,
            splice_threshold=45,
            path_precision=3
        )

        # 4. READ RESULTS AND CLEANUP
        with open(temp_svg_path, "r") as svg_file:
            svg_content = svg_file.read()

        # Scrub any rogue white backgrounds generated by tracer to guarantee transparency
        svg_content = re.sub(r'<path[^>]*fill=["\']?(?:rgb\(\s*255\s*,\s*255\s*,\s*255\s*\)|#ffffff|#fff)["\']?[^>]*\/?>(?:<\/path>)?', '', svg_content, flags=re.IGNORECASE)
        
        # Add XML headers if missing
        if not svg_content.strip().startswith("<?xml"):
            svg_content = '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n<!-- Generated by VectorAI V4 -->\n' + svg_content

        png_base64 = base64.b64encode(bg_removed_data).decode('utf-8')
        
        print("[AI Engine V4] ✅ Successfully generated PNG & SVG!")

        return jsonify({
            "status": "success",
            "png_base64": f"data:image/png;base64,{png_base64}",
            "svg_content": svg_content
        })

    except Exception as e:
        print(f"[ERROR] {str(e)}")
        return jsonify({'detail': str(e)}), 500

    finally:
        # 5. GUARANTEED CLEANUP (Runs even if an error occurs)
        if temp_png_path and os.path.exists(temp_png_path):
            os.remove(temp_png_path)
        if temp_svg_path and os.path.exists(temp_svg_path):
            os.remove(temp_svg_path)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000, debug=True)